---
output: 
  md_document:
    variant: markdown_github
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# Korean Votes

The goal of `krvotes` is to provide the Korean votes information. 

## Installation

You can install the devloping version of `krvotes` from [github](https://github.com/statkclee/krvotes) with:

``` r
# install.packages('remotes')
remotes::install_github("statkclee/krvotes")
```

### 국회의원 선거 - 2016

```{r krvotes-congressman}
# load package
library(krvotes)
suppressMessages(library(tidyverse))

# 국회의원 선거 (2016)
congress_df <- congress_2018

# 지역구: 경기도 성남시 분당구 을

congress_df %>%
    filter(sido == "경기" & precinct == "성남시분당구을") %>%
    pull(data_clean) %>% .[[1]] %>%
    summarise(`더불어민주당 김병욱` = sum(`더불어민주당 김병욱`),
              `새누리당 전하진`     = sum(`새누리당 전하진`),
              `국민의당 윤은숙`     = sum(`국민의당 윤은숙`),
              `무소속 임태희`       = sum(`무소속 임태희`))
```


## 대통령 선거 - 2017

```{r krvotes-president}
# read presidential votes 2018 and assign it to president_df
president_df <- president
# check the structure of the object
str(object = president_df)
```

## 지방선거 선거 - 2018

### 시도지사 득표

```{r krvotes-local-province}
local_2018_df <- local_2018

jeju_df <- local_2018_df %>%
  filter(str_detect(precinct, "제주")) %>%
  pull(data_clean) %>%
  .[[1]]

jeju_df %>%
  summarize(`문대림` = sum(democracy))
```

### 시군구장 득표

```{r krvotes-local-mayor}
local_sigungu_df <- local_sigungu_2018

changwon_df <- local_sigungu_df %>% 
  filter(str_detect(precinct, "창원")) %>% 
  select(data_clean) %>% 
  unnest()

changwon_df %>% 
  filter(str_detect(sigungu, "성산")) %>% 
  summarise(`허성무` = sum(`더불어민주당 허성무`),
            `조진래` = sum(`자유한국당 조진래`),
            `정규헌` = sum(`바른미래당 정규헌`),
            `석영철` = sum(`민중당 석영철`),
            `안상수` = sum(`무소속 안상수`),
            `이기우` = sum(`무소속 이기우`))
```

- [중앙선거관리위원회 - 선거통계시스템](http://info.nec.go.kr/) 

역대선거 &rarr; 지방선거 &rarr; 제7회 &rarr; 구시군의 장선거 &rarr; 경상남도 &rarr; 창원시 &rarr; 창원시성산구

|   후보              | 득표수  |
|---------------------|---------|
| 더불어민주당 허성무	|  68,023	|
| 자유한국당 조진래	  |  29,669 |
| 바른미래당 정규헌	  |   3,202	|
| 민중당 석영철	      |   4,139	|
| 무소속 안상수	      |  16,282 |
| 무소속 이기우				|   2,782 |


